Feature/csl703 no dht key
serokell/kademlia pull request #14
Opened 2017-05-27 15:17 UTC by pva701

* Now node is identified Peer (pair ip:port) from outside.
* Store inside kademlia map from Peer to NodeId

2017-05-27 17:04 UTC, georgeee requested changes

2017-05-27 17:04 UTC, georgeee commented on src/Network/Kademlia/Implementation.hs
> +        rest <- resolveNodeIds inst (polled \\ known)
I don't understand how  we can guarantee that nodes from `polled` are contained in buckets

2017-05-27 17:04 UTC, georgeee commented on src/Network/Kademlia/Implementation.hs
> +    sendS toPeer = liftIO ownId >>= flip sendSignal toPeer . FIND_NODE
`toPeer` sounds like a function , let's leave  just `peer`

2017-05-27 17:05 UTC, georgeee commented on src/Network/Kademlia/Implementation.hs
> +        rest <- resolveNodeIds inst (polled \\ known)
Or explain why we don't need his guarantee

2017-05-27 17:27 UTC, pva701 commented on src/Network/Kademlia/Implementation.hs
> +        rest <- resolveNodeIds inst (polled \\ known)
We can guarantee.
1. We add `peer` to `polled` when call `sendSignal`
2a. when we call `sendSignal` at `startLookup`, we always calls `waitForReply` which does `insertNode` at the beginning or
2b. when we call `sendSignal` at `continueLookup` we every time call `continue`, but `continue=waitForReply` everywhere.
So we always call `waitForReply` which guarantee that a node will be inserted before any other actions.
Verify plz, and if it's true, I can add this comment to Kademlia.

2017-05-27 18:37 UTC, georgeee commented on src/Network/Kademlia/Implementation.hs
> +        rest <- resolveNodeIds inst (polled \\ known)
But the fact we call `insertNode` doesn't imply node gets to any bucket. Appropriate bucket may be full for instance

2017-05-28 00:34 UTC, georgeee approved these changes

2017-05-28 00:34 UTC, georgeee commented on src/Network/Kademlia/Implementation.hs
> +                when firstTime $ do
rename `firstTime` param to something like `withinJoin`

2017-05-28 00:34 UTC, georgeee commented on src/Network/Kademlia/ReplyQueue.hs
> +    -- ^ Channel for initial receiving of messages.
What about renaming it to `dispatchChan`?

2017-05-28 20:06 UTC, merged